<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php //echo '<pre>';print_r($_item->getData());?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
	<td>
<?php $product =  $_item->getProduct();?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();?>

<?php  $imagewidth=200;
$imageheight=200;
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
$image_url = '';
if($product!='' && $product!=NULL){ 
$image_url = $imageHelper->init($product, 'small_image')->setImageFile($product->getSmallImage())->getUrl(); }
?>
<?php if($image_url!='' && $image_url!=NULL){ ?>
<a href="<?php echo $product->getProductUrl();?>" target="_blank"><img src="<?php echo $image_url;?>" /></a>
<?php } ?>
</td>
 
<td>
<?php //$_product =  $_item->getProduct();
//echo '<pre>';print_r($product->getId());exit;
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$productObj = $productRepository->get($_item->getSku());
$getInternalSku = $productObj->getInternalSku();
?>
<?php if($getInternalSku!='' && $getInternalSku!=NULL){ 
echo $getInternalSku;
 } ?>
</td>
    <?php foreach ($columns as $columnName => $columnClass) : ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
            <?= $block->getColumnHtml($_item, $columnName) ?>
        </td>
    <?php endforeach; ?>
</tr>
